# default
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      #names: ${job.name:NONE}
      name: ${job.name:NONE}
      enabled: false # 프로젝트 실행 시 job.name 파라미터가 존재하더라도 특정 job이 실행되지 않음 -> 스케쥴링 이용
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ldcc!2626
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2